//所有y需要根据UI图标注再加上顶部40
export default [{
    //教材名称
    "name": "IsLand",
    //单元A牌子及大小
    "unitUrl": "static/course/island/island1/img_unit_bg.png",
    "width": 503,
    "height": 406,
    "units": [{
        "imgUrl": "static/course/island/island1/img_U1.png", //地图
        //单元A牌子位置
        "x": 720,
        "y": 1070,
        //单元B三段图片(加锁)
        "chapter": {
            "leftUrl": "static/course/island/img_UB_01.png",
            "middleUrl": "static/course/island/img_UB_02.png",
            "rightUrl": "static/course/island/img_UB_03.png",
            "leftLockUrl": "static/course/island/img_UB_01_lock.png",
            "middleLockUrl": "static/course/island/img_UB_02_lock.png",
            "rightLockUrl": "static/course/island/img_UB_03_lock.png",
            "color": "#165eb6",
            "lw": 134, //第一段width
            "rw": 54, //第三段width
            "h": 131, //1，2，3 height
            "ml": 70, // 单元A ml
            "mt": 24, // 单元A mt
        },
        //单元B位置
        "chapters": [{
            "x": 366,
            "y": 220
        }, {
            "x": 140,
            "y": 580
        }, {
            "x": 562,
            "y": 840
        }, {
            "x": 940,
            "y": 500
        }, {
            "x": 1320,
            "y": 880
        }, {
            "x": 1436,
            "y": 640
        }]
    }, {
        "imgUrl": "static/course/island/island1/img_U2.png",
        "x": 70,
        "y": 1010,
        "chapters": [{
            "x": 130,
            "y": 790
        }, {
            "x": 564,
            "y": 480
        }, {
            "x": 730,
            "y": 720
        }, {
            "x": 850,
            "y": 1060
        }, {
            "x": 1380,
            "y": 730
        }, {
            "x": 1436,
            "y": 380
        }]
    }, {
        "imgUrl": "static/course/island/island1/img_U3.png",
        "x": 790,
        "y": 960,
        "chapters": [{
            "x": 60,
            "y": 460
        }, {
            "x": 320,
            "y": 750
        }, {
            "x": 580,
            "y": 530
        }, {
            "x": 1000,
            "y": 260
        }, {
            "x": 1340,
            "y": 620
        }, {
            "x": 1436,
            "y": 920
        }]
    }, {
        "imgUrl": "static/course/island/island1/img_U4.png",
        "x": 1030,
        "y": 1100,
        "chapters": [{
            "x": 60,
            "y": 780
        }, {
            "x": 240,
            "y": 510
        }, {
            "x": 660,
            "y": 320
        }, {
            "x": 900,
            "y": 630
        }, {
            "x": 1320,
            "y": 830
        }, {
            "x": 1436,
            "y": 500
        }]
    }, {
        "imgUrl": "static/course/island/island1/img_U5.png",
        "x": 470,
        "y": 70,
        "chapters": [{
            "x": 50,
            "y": 910
        }, {
            "x": 300,
            "y": 1140
        }, {
            "x": 710,
            "y": 810
        }, {
            "x": 1250,
            "y": 1010
        }, {
            "x": 1426,
            "y": 700
        }, {
            "x": 1436,
            "y": 430
        }]
    }, {
        "imgUrl": "static/course/island/island1/img_U6.png",
        "x": 1300,
        "y": 70,
        "chapters": [{
            "x": 70,
            "y": 370
        }, {
            "x": 250,
            "y": 590
        }, {
            "x": 770,
            "y": 680
        }, {
            "x": 1030,
            "y": 920
        }, {
            "x": 1290,
            "y": 1150
        }, {
            "x": 1436,
            "y": 1260
        }]
    }, {
        "imgUrl": "static/course/island/island1/img_U7.png",
        "x": 1470,
        "y": 1090,
        "chapters": [{
            "x": 260,
            "y": 730
        }, {
            "x": 840,
            "y": 1010
        }, {
            "x": 1436,
            "y": 560
        }]
    }]
}, {
    "name": "IsLand",
    "unitUrl": "static/course/island/island2/img_unit_bg.png",
    "width": 361,
    "height": 448,
    "units": [{
        "imgUrl": "static/course/island/island2/img_U1.png",
        "x": 1030,
        "y": 1080,
        "chapter": {
            "leftUrl": "static/course/island/img_UB_01.png",
            "middleUrl": "static/course/island/img_UB_02.png",
            "rightUrl": "static/course/island/img_UB_03.png",
            "leftLockUrl": "static/course/island/img_UB_01_lock.png",
            "middleLockUrl": "static/course/island/img_UB_02_lock.png",
            "rightLockUrl": "static/course/island/img_UB_03_lock.png",
            "color": "#165eb6",
            "lw": 134,
            "rw": 54,
            "h": 131,
            "ml": 70,
            "mt": 24,
        },
        "chapters": [{
            "x": 90,
            "y": 580
        }, {
            "x": 450,
            "y": 860
        }, {
            "x": 980,
            "y": 410
        }, {
            "x": 1170,
            "y": 710
        }, {
            "x": 1380,
            "y": 910
        }, {
            "x": 1436,
            "y": 565
        }]
    }, {
        "imgUrl": "static/course/island/island2/img_U2.png",
        "x": 1350,
        "y": 1120,
        "chapters": [{
            "x": 80,
            "y": 800
        }, {
            "x": 400,
            "y": 580
        }, {
            "x": 670,
            "y": 300
        }, {
            "x": 940,
            "y": 700
        }, {
            "x": 1200,
            "y": 940
        }, {
            "x": 1436,
            "y": 630
        }]
    }, {
        "imgUrl": "static/course/island/island2/img_U3.png",
        "x": 870,
        "y": 90,
        "chapters": [{
            "x": 70,
            "y": 1110
        }, {
            "x": 480,
            "y": 840
        }, {
            "x": 970,
            "y": 1000
        }, {
            "x": 1220,
            "y": 730
        }, {
            "x": 1360,
            "y": 460
        }, {
            "x": 1436,
            "y": 270
        }]
    }, {
        "imgUrl": "static/course/island/island2/img_U4.png",
        "x": 1320,
        "y": 1120,
        "chapters": [{
            "x": 70,
            "y": 440
        }, {
            "x": 340,
            "y": 680
        }, {
            "x": 460,
            "y": 870
        }, {
            "x": 780,
            "y": 1080
        }, {
            "x": 1250,
            "y": 830
        }, {
            "x": 1436,
            "y": 670
        }]
    }, {
        "imgUrl": "static/course/island/island2/img_U5.png",
        "x": 930,
        "y": 70,
        "chapters": [{
            "x": 80,
            "y": 720
        }, {
            "x": 270,
            "y": 1000
        }, {
            "x": 720,
            "y": 590
        }, {
            "x": 1070,
            "y": 790
        }, {
            "x": 1460,
            "y": 962
        }, {
            "x": 1436,
            "y": 1210
        }]
    }, {
        "imgUrl": "static/course/island/island2/img_U6.png",
        "x": 1150,
        "y": 70,
        "chapters": [{
            "x": 100,
            "y": 980
        }, {
            "x": 550,
            "y": 1220
        }, {
            "x": 890,
            "y": 710
        }, {
            "x": 1170,
            "y": 990
        }, {
            "x": 1426,
            "y": 790
        }, {
            "x": 1436,
            "y": 560
        }]
    }, {
        "imgUrl": "static/course/island/island2/img_U7.png",
        "x": 140,
        "y": 70,
        "chapters": [{
            "x": 330,
            "y": 658
        }, {
            "x": 840,
            "y": 1010
        }, {
            "x": 1436,
            "y": 750
        }]
    }]
}, {
    "name": "IsLand",
    "unitUrl": "static/course/island/island3/img_unit_bg.png",
    "width": 361,
    "height": 448,
    "units": [{
        "imgUrl": "static/course/island/island3/img_U1.png",
        "x": 410,
        "y": 110,
        "chapter": {
            "leftUrl": "static/course/island/img_UB_01.png",
            "middleUrl": "static/course/island/img_UB_02.png",
            "rightUrl": "static/course/island/img_UB_03.png",
            "leftLockUrl": "static/course/island/img_UB_01_lock.png",
            "middleLockUrl": "static/course/island/img_UB_02_lock.png",
            "rightLockUrl": "static/course/island/img_UB_03_lock.png",
            "color": "#165eb6",
            "lw": 134,
            "rw": 54,
            "h": 131,
            "ml": 70,
            "mt": 24,
        },
        "chapters": [{
            "x": 180,
            "y": 1200
        }, {
            "x": 500,
            "y": 860
        }, {
            "x": 720,
            "y": 570
        }, {
            "x": 1080,
            "y": 830
        }, {
            "x": 1320,
            "y": 1240
        }, {
            "x": 1436,
            "y": 960
        }]
    }, {
        "imgUrl": "static/course/island/island3/img_U2.png",
        "x": 580,
        "y": 960,
        "chapters": [{
            "x": 60,
            "y": 970
        }, {
            "x": 430,
            "y": 700
        }, {
            "x": 630,
            "y": 460
        }, {
            "x": 1000,
            "y": 220
        }, {
            "x": 1320,
            "y": 440
        }, {
            "x": 1436,
            "y": 680
        }]
    }, {
        "imgUrl": "static/course/island/island3/img_U3.png",
        "x": 490,
        "y": 1100,
        "chapters": [{
            "x": 60,
            "y": 890
        }, {
            "x": 360,
            "y": 710
        }, {
            "x": 620,
            "y": 540
        }, {
            "x": 1020,
            "y": 790
        }, {
            "x": 1280,
            "y": 1030
        }, {
            "x": 1436,
            "y": 800
        }]
    }, {
        "imgUrl": "static/course/island/island3/img_U4.png",
        "x": 1330,
        "y": 1130,
        "chapters": [{
            "x": 70,
            "y": 700
        }, {
            "x": 480,
            "y": 460
        }, {
            "x": 790,
            "y": 700
        }, {
            "x": 840,
            "y": 1030
        }, {
            "x": 1290,
            "y": 890
        }, {
            "x": 1436,
            "y": 670
        }]
    }, {
        "imgUrl": "static/course/island/island3/img_U5.png",
        "x": 920,
        "y": 100,
        "chapters": [{
            "x": 70,
            "y": 700
        }, {
            "x": 140,
            "y": 980
        }, {
            "x": 420,
            "y": 1210
        }, {
            "x": 840,
            "y": 920
        }, {
            "x": 1060,
            "y": 610
        }, {
            "x": 1436,
            "y": 420
        }]
    }, {
        "imgUrl": "static/course/island/island3/img_U6.png",
        "x": 260,
        "y": 820,
        "chapters": [{
            "x": 70,
            "y": 540
        }, {
            "x": 490,
            "y": 390
        }, {
            "x": 740,
            "y": 670
        }, {
            "x": 980,
            "y": 970
        }, {
            "x": 1340,
            "y": 810
        }, {
            "x": 1436,
            "y": 610
        }]
    }, {
        "imgUrl": "static/course/island/island3/img_U7.png",
        "x": 360,
        "y": 1010,
        "chapters": [{
            "x": 180,
            "y": 610
        }, {
            "x": 810,
            "y": 360
        }, {
            "x": 1280,
            "y": 870
        }]
    }]
}, {
    "name": "IsLand",
    "unitUrl": "static/course/island/island4/img_unit_bg.png",
    "width": 361,
    "height": 448,
    "units": [{
        "imgUrl": "static/course/island/island4/img_U1.png",
        "x": 780,
        "y": 80,
        "chapter": {
            "leftUrl": "static/course/island/img_UB_01.png",
            "middleUrl": "static/course/island/img_UB_02.png",
            "rightUrl": "static/course/island/img_UB_03.png",
            "leftLockUrl": "static/course/island/img_UB_01_lock.png",
            "middleLockUrl": "static/course/island/img_UB_02_lock.png",
            "rightLockUrl": "static/course/island/img_UB_03_lock.png",
            "color": "#165eb6",
            "lw": 134,
            "rw": 54,
            "h": 131,
            "ml": 70,
            "mt": 24,
        },
        "chapters": [{
            "x": 76,
            "y": 1070
        }, {
            "x": 460,
            "y": 860
        }, {
            "x": 720,
            "y": 564
        }, {
            "x": 1030,
            "y": 815
        }, {
            "x": 1280,
            "y": 1240
        }, {
            "x": 1436,
            "y": 910
        }]
    }, {
        "imgUrl": "static/course/island/island4/img_U2.png",
        "x": 860,
        "y": 970,
        "chapters": [{
            "x": 100,
            "y": 740
        }, {
            "x": 480,
            "y": 560
        }, {
            "x": 670,
            "y": 380
        }, {
            "x": 1110,
            "y": 670
        }, {
            "x": 1300,
            "y": 920
        }, {
            "x": 1436,
            "y": 1170
        }]
    }, {
        "imgUrl": "static/course/island/island4/img_U3.png",
        "x": 510,
        "y": 1070,
        "chapters": [{
            "x": 60,
            "y": 930
        }, {
            "x": 380,
            "y": 660
        }, {
            "x": 890,
            "y": 820
        }, {
            "x": 1100,
            "y": 590
        }, {
            "x": 780,
            "y": 380
        }, {
            "x": 1436,
            "y": 700
        }]
    }, {
        "imgUrl": "static/course/island/island4/img_U4.png",
        "x": 50,
        "y": 790,
        "chapters": [{
            "x": 60,
            "y": 400
        }, {
            "x": 420,
            "y": 230
        }, {
            "x": 610,
            "y": 440
        }, {
            "x": 670,
            "y": 740
        }, {
            "x": 1300,
            "y": 650
        }, {
            "x": 1436,
            "y": 930
        }]
    }, {
        "imgUrl": "static/course/island/island4/img_U5.png",
        "x": 1160,
        "y": 950,
        "chapters": [{
            "x": 90,
            "y": 850
        }, {
            "x": 290,
            "y": 590
        }, {
            "x": 680,
            "y": 770
        }, {
            "x": 1000,
            "y": 420
        }, {
            "x": 1380,
            "y": 640
        }, {
            "x": 1436,
            "y": 870
        }]
    }, {
        "imgUrl": "static/course/island/island4/img_U6.png",
        "x": 1520,
        "y": 1060,
        "chapters": [{
            "x": 70,
            "y": 870
        }, {
            "x": 340,
            "y": 590
        }, {
            "x": 770,
            "y": 760
        }, {
            "x": 980,
            "y": 390
        }, {
            "x": 1400,
            "y": 570
        }, {
            "x": 1436,
            "y": 840
        }]
    }, {
        "imgUrl": "static/course/island/island4/img_U7.png",
        "x": 1190,
        "y": 340,
        "chapters": [{
            "x": 180,
            "y": 1120
        }, {
            "x": 700,
            "y": 650
        }, {
            "x": 1170,
            "y": 970
        }]
    }]
}, {
    "name": "FunFair",
    "unitUrl": "static/course/funfair/funfair1/img_unit1_bg@2x.png",
    "width": 513,
    "height": 407,
    "units": [{
        "imgUrl": "static/course/funfair/funfair1/funfair1_U1@2x.png",
        "x": 1316,
        "y": 1126,
        "chapter": {
            "leftUrl": "static/course/funfair/img_UB_01@2x.png",
            "middleUrl": "static/course/funfair/img_UB_02@2x.png",
            "rightUrl": "static/course/funfair/img_UB_03@2x.png",
            "leftLockUrl": "static/course/funfair/img_UB_01_lock@2x.png",
            "middleLockUrl": "static/course/funfair/img_UB_02_lock@2x.png",
            "rightLockUrl": "static/course/funfair/img_UB_03_lock@2x.png",
            "color": "#11541A",
            "lw": 87,
            "rw": 45,
            "h": 106,
            "ml": 140,
            "mt": 50
        },
        "chapters": [{
            "x": 336,
            "y": 478
        }, {
            "x": 190,
            "y": 698
        }, {
            "x": 386,
            "y": 908
        }, {
            "x": 514,
            "y": 1160
        }, {
            "x": 886,
            "y": 1050
        }, {
            "x": 1300,
            "y": 940
        }, {
            "x": 1446,
            "y": 758
        }, {
            "x": 1470,
            "y": 600
        }]
    }, {
        "imgUrl": "static/course/funfair/funfair1/funfair1_U2@2x.png",
        "x": 1316,
        "y": 1126,
        "chapters": [{
            "x": 406,
            "y": 482
        }, {
            "x": 282,
            "y": 662
        }, {
            "x": 602,
            "y": 796
        }, {
            "x": 550,
            "y": 962
        }, {
            "x": 904,
            "y": 1120
        }, {
            "x": 1324,
            "y": 994
        }, {
            "x": 1446,
            "y": 758
        }, {
            "x": 1470,
            "y": 600
        }]
    }, {
        "imgUrl": "static/course/funfair/funfair1/funfair1_U3@2x.png",
        "x": 1316,
        "y": 1126,
        "chapters": [{
            "x": 298,
            "y": 444
        }, {
            "x": 530,
            "y": 642
        }, {
            "x": 454,
            "y": 820
        }, {
            "x": 508,
            "y": 1120
        }, {
            "x": 828,
            "y": 998
        }, {
            "x": 1014,
            "y": 812
        }, {
            "x": 1470,
            "y": 890
        }, {
            "x": 1470,
            "y": 634
        }]
    }, {
        "imgUrl": "static/course/funfair/funfair1/funfair1_U4@2x.png",
        "x": 1316,
        "y": 1126,
        "chapters": [{
            "x": 308,
            "y": 490
        }, {
            "x": 300,
            "y": 736
        }, {
            "x": 456,
            "y": 942
        }, {
            "x": 854,
            "y": 1070
        }, {
            "x": 956,
            "y": 888
        }, {
            "x": 1416,
            "y": 946
        }, {
            "x": 1436,
            "y": 754
        }, {
            "x": 1470,
            "y": 588
        }]
    }, {
        "imgUrl": "static/course/funfair/funfair1/funfair1_U5@2x.png",
        "x": 1316,
        "y": 1126,
        "chapters": [{
            "x": 308,
            "y": 488
        }, {
            "x": 356,
            "y": 688
        }, {
            "x": 356,
            "y": 890
        }, {
            "x": 518,
            "y": 1054
        }, {
            "x": 880,
            "y": 1160
        }, {
            "x": 1184,
            "y": 944
        }, {
            "x": 1372,
            "y": 776
        }, {
            "x": 1470,
            "y": 608
        }]
    }, {
        "imgUrl": "static/course/funfair/funfair1/funfair1_U6@2x.png",
        "x": 1316,
        "y": 1126,
        "chapters": [{
            "x": 346,
            "y": 716
        }, {
            "x": 926,
            "y": 976
        }, {
            "x": 1450,
            "y": 796
        }]
    }]
}, {
    "name": "FunFair",
    "unitUrl": "static/course/funfair/funfair2/img_unit2_bg@2x.png",
    "width": 514,
    "height": 480,
    "units": [{
        "imgUrl": "static/course/funfair/funfair2/funfair2_U1@2x.png",
        "x": 1522,
        "y": 544,
        "chapter": {
            "leftUrl": "static/course/funfair/img_UB_01@2x.png",
            "middleUrl": "static/course/funfair/img_UB_02@2x.png",
            "rightUrl": "static/course/funfair/img_UB_03@2x.png",
            "leftLockUrl": "static/course/funfair/img_UB_01_lock@2x.png",
            "middleLockUrl": "static/course/funfair/img_UB_02_lock@2x.png",
            "rightLockUrl": "static/course/funfair/img_UB_03_lock@2x.png",
            "color": "#11541A",
            "lw": 87,
            "rw": 45,
            "h": 106,
            "ml": 140,
            "mt": 50
        },
        "chapters": [{
            "x": 40,
            "y": 854
        }, {
            "x": 266,
            "y": 1234
        }, {
            "x": 549,
            "y": 968
        }, {
            "x": 772,
            "y": 1320
        }, {
            "x": 1076,
            "y": 1132
        }, {
            "x": 1196,
            "y": 816
        }, {
            "x": 1442,
            "y": 984
        }, {
            "x": 1470,
            "y": 1240
        }]
    }, {
        "imgUrl": "static/course/funfair/funfair2/funfair2_U2@2x.png",
        "x": 1505,
        "y": 532,
        "chapters": [{
            "x": 42,
            "y": 856
        }, {
            "x": 234,
            "y": 1194
        }, {
            "x": 544,
            "y": 948
        }, {
            "x": 740,
            "y": 1234
        }, {
            "x": 980,
            "y": 1018
        }, {
            "x": 1222,
            "y": 788
        }, {
            "x": 1470,
            "y": 1082
        }, {
            "x": 1470,
            "y": 1314
        }]
    }, {
        "imgUrl": "static/course/funfair/funfair2/funfair2_U3@2x.png",
        "x": 1380,
        "y": 390,
        "chapters": [{
            "x": 70,
            "y": 836
        }, {
            "x": 252,
            "y": 1118
        }, {
            "x": 694,
            "y": 742
        }, {
            "x": 828,
            "y": 1178
        }, {
            "x": 1070,
            "y": 1028
        }, {
            "x": 1344,
            "y": 882
        }, {
            "x": 1460,
            "y": 1128
        }, {
            "x": 1470,
            "y": 1360
        }]
    }, {
        "imgUrl": "static/course/funfair/funfair2/funfair2_U4@2x.png",
        "x": 1488,
        "y": 270,
        "chapters": [{
            "x": 78,
            "y": 874
        }, {
            "x": 216,
            "y": 1200
        }, {
            "x": 584,
            "y": 972
        }, {
            "x": 800,
            "y": 1286
        }, {
            "x": 1024,
            "y": 1028
        }, {
            "x": 1439,
            "y": 1187
        }, {
            "x": 1434,
            "y": 910
        }, {
            "x": 1470,
            "y": 718
        }]
    }, {
        "imgUrl": "static/course/funfair/funfair2/funfair2_U5@2x.png",
        "x": 1488,
        "y": 320,
        "chapters": [{
            "x": 40,
            "y": 1156
        }, {
            "x": 344,
            "y": 916
        }, {
            "x": 582,
            "y": 1076
        }, {
            "x": 910,
            "y": 1240
        }, {
            "x": 1066,
            "y": 998
        }, {
            "x": 1500,
            "y": 1242
        }, {
            "x": 1554,
            "y": 976
        }, {
            "x": 1470,
            "y": 786
        }]
    }, {
        "imgUrl": "static/course/funfair/funfair2/funfair2_U6@2x.png",
        "x": 1500,
        "y": 576,
        "chapters": [{
            "x": 288,
            "y": 896
        }, {
            "x": 766,
            "y": 1162
        }, {
            "x": 1164,
            "y": 994
        }]
    }]
}, {
    "name": "FunFair",
    "unitUrl": "static/course/funfair/funfair3/img_unit3_bg@2x.png",
    "width": 513,
    "height": 407,
    "units": [{
        "imgUrl": "static/course/funfair/funfair3/funfair3_U1@2x.png",
        "x": 1316,
        "y": 1126,
        "chapter": {
            "leftUrl": "static/course/funfair/img_UB_01@2x.png",
            "middleUrl": "static/course/funfair/img_UB_02@2x.png",
            "rightUrl": "static/course/funfair/img_UB_03@2x.png",
            "leftLockUrl": "static/course/funfair/img_UB_01_lock@2x.png",
            "middleLockUrl": "static/course/funfair/img_UB_02_lock@2x.png",
            "rightLockUrl": "static/course/funfair/img_UB_03_lock@2x.png",
            "color": "#11541A",
            "lw": 87,
            "rw": 45,
            "h": 106,
            "ml": 140,
            "mt": 50
        },
        "chapters": [{
            "x": 272,
            "y": 618
        }, {
            "x": 406,
            "y": 824
        }, {
            "x": 370,
            "y": 1042
        }, {
            "x": 734,
            "y": 1174
        }, {
            "x": 887,
            "y": 980
        }, {
            "x": 1436,
            "y": 980
        }, {
            "x": 1456,
            "y": 786
        }, {
            "x": 1470,
            "y": 618
        }]
    }, {
        "imgUrl": "static/course/funfair/funfair3/funfair3_U2@2x.png",
        "x": 1316,
        "y": 1126,
        "chapters": [{
            "x": 410,
            "y": 502
        }, {
            "x": 286,
            "y": 662
        }, {
            "x": 608,
            "y": 808
        }, {
            "x": 555,
            "y": 982
        }, {
            "x": 899,
            "y": 1140
        }, {
            "x": 1220,
            "y": 994
        }, {
            "x": 1470,
            "y": 778
        }, {
            "x": 1470,
            "y": 620
        }]
    }, {
        "imgUrl": "static/course/funfair/funfair3/funfair3_U3@2x.png",
        "x": 1316,
        "y": 1126,
        "chapters": [{
            "x": 300,
            "y": 450
        }, {
            "x": 532,
            "y": 610
        }, {
            "x": 456,
            "y": 828
        }, {
            "x": 510,
            "y": 1128
        }, {
            "x": 830,
            "y": 996
        }, {
            "x": 1014,
            "y": 820
        }, {
            "x": 1470,
            "y": 898
        }, {
            "x": 1470,
            "y": 642
        }]
    }, {
        "imgUrl": "static/course/funfair/funfair3/funfair3_U4@2x.png",
        "x": 1316,
        "y": 1126,
        "chapters": [{
            "x": 322,
            "y": 514
        }, {
            "x": 314,
            "y": 762
        }, {
            "x": 470,
            "y": 968
        }, {
            "x": 868,
            "y": 1097
        }, {
            "x": 970,
            "y": 904
        }, {
            "x": 1428,
            "y": 760
        }, {
            "x": 1470,
            "y": 614
        }]
    }, {
        "imgUrl": "static/course/funfair/funfair3/funfair3_U5@2x.png",
        "x": 1316,
        "y": 1126,
        "chapters": [{
            "x": 310,
            "y": 484
        }, {
            "x": 356,
            "y": 684
        }, {
            "x": 356,
            "y": 886
        }, {
            "x": 530,
            "y": 1068
        }, {
            "x": 880,
            "y": 1102
        }, {
            "x": 1188,
            "y": 940
        }, {
            "x": 1378,
            "y": 773
        }, {
            "x": 1470,
            "y": 604
        }]
    }, {
        "imgUrl": "static/course/funfair/funfair3/funfair3_U6@2x.png",
        "x": 1316,
        "y": 1126,
        "chapters": [{
            "x": 300,
            "y": 662
        }, {
            "x": 1136,
            "y": 998
        }, {
            "x": 1438,
            "y": 754
        }]
    }]
}];